name: First Workflow
on: [push, workflow_dispatch]
jobs:
  first-job:
    runs-on: unbuntu-latest
    steps:
      - name: First step
        run: echo "First Step"
      - name: Second step
        run: echo "Second Step"
