name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: unbuntu-latest
    steps:
      - name: First step
        run: echo "First Step"
      - name: Second step
        run: echo "Second step"
